//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE_LOTE
    {
        public int Id { get; set; }
        public int LOTEId { get; set; }
        public int CLIENTEId { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int USUARIOId { get; set; }
        public decimal MontoRestante { get; set; }
        public int NoPagos { get; set; }
        public bool ExcedePlazoPago { get; set; }
        public string FechaExcedePlazo { get; set; }
        public Nullable<decimal> MontoExcedePlazo { get; set; }
        public Nullable<int> NoPagosExcede { get; set; }
    
        public virtual LOTE LOTE { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual USUARIO USUARIOASIGNO { get; set; }
    }
}
