//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTELOTE
    {
        public int Id { get; set; }
        public string Folio { get; set; }
        public string FechaArrendamiento { get; set; }
        public int CLIENTEId { get; set; }
        public int LOTEId { get; set; }
        public int USUARIOOperacionId { get; set; }
        public int NoPagos { get; set; }
        public decimal PrecioInicial { get; set; }
        public int DiaPago { get; set; }
        public Nullable<System.DateTime> FechaReimpresion { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual LOTE LOTE { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
