//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTRATO()
        {
            this.CONTRATO_LOTES = new HashSet<CONTRATO_LOTES>();
        }
    
        public int Id { get; set; }
        public string Folio { get; set; }
        public System.DateTime FechaArrendamiento { get; set; }
        public int CLIENTEId { get; set; }
        public Nullable<int> SOCIOSId { get; set; }
        public int NoPagos { get; set; }
        public decimal PrecioInicial { get; set; }
        public int DiaPago { get; set; }
        public decimal PagoInicial { get; set; }
        public int NoPagosGracia { get; set; }
        public Nullable<decimal> MontoGracia { get; set; }
        public int ESTADOId { get; set; }
        public string Observacion { get; set; }
        public int USUARIOOperacionId { get; set; }
        public Nullable<System.DateTime> FechaReimpresion { get; set; }
        public Nullable<System.DateTime> FechaInicioProrroga { get; set; }
        public string ColindaNorte { get; set; }
        public string ColindaSur { get; set; }
        public string ColindaEste { get; set; }
        public string ColindaOeste { get; set; }
        public decimal MideNorte { get; set; }
        public decimal MideSur { get; set; }
        public decimal MideEste { get; set; }
        public decimal MideOeste { get; set; }
        public int AGENDAId { get; set; }
        public Nullable<int> CONTRATOId { get; set; }
        public Nullable<decimal> MontoReicision { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual SOCIOS SOCIOS { get; set; }
        public virtual ESTADO ESTADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRATO_LOTES> CONTRATO_LOTES { get; set; }
        public virtual AGENDA AGENDA { get; set; }
        public virtual CONTRATO CONTRATOORIGEN { get; set; }
    }
}
