//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTROL_PERMISO
    {
        public int Id { get; set; }
        public int CONTROLId { get; set; }
        public int USUARIOSOLICITAId { get; set; }
        public int USUARIOASIGNOId { get; set; }
        public string Visible { get; set; }
        public string Enabled { get; set; }
        public bool Readonly { get; set; }
        public string FechaRegistro { get; set; }
    
        public virtual CONTROL CONTROL { get; set; }
        public virtual USUARIO USUARIOSOLICITA { get; set; }
        public virtual USUARIO USUARIOASIGNO { get; set; }
    }
}
