//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOTE
    {
        public int Id { get; set; }
        public string Identificador { get; set; }
        public int ZONAId { get; set; }
        public Nullable<int> Manzana { get; set; }
        public string NoLote { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public decimal Precio { get; set; }
        public int ESTADOId { get; set; }
    
        public virtual ZONA ZONA { get; set; }
        public virtual ESTADO ESTADO { get; set; }
    }
}
