//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOTE
    {
        public int Id { get; set; }
        public int ZONAId { get; set; }
        public decimal MNorte { get; set; }
        public decimal MSur { get; set; }
        public decimal MOeste { get; set; }
        public decimal MEste { get; set; }
        public string CNorte { get; set; }
        public string CSur { get; set; }
        public string COeste { get; set; }
        public string CEste { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public decimal Precio { get; set; }
    
        public virtual ZONA ZONA { get; set; }
    }
}
