//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO
    {
        public int Id { get; set; }
        public string NumeroReferencia { get; set; }
        public System.DateTime FechaEmison { get; set; }
        public int CLIENTEId { get; set; }
        public int LOTEId { get; set; }
        public decimal Monto { get; set; }
        public int USUARIORECIBEPAGOId { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual LOTE LOTE { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
