//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO
    {
        public int Id { get; set; }
        public string Folio { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public int ContratoId { get; set; }
        public int USUARIORecibeId { get; set; }
        public decimal Monto { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        public virtual CLIENTELOTE CLIENTELOTE { get; set; }
    }
}
