//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROL_PERMISO
    {
        public int Id { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public int MODULOId { get; set; }
        public int ROLId { get; set; }
    
        public virtual MODULO MODULO { get; set; }
        public virtual ROL ROL { get; set; }
    }
}
