//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int Id { get; set; }
        public string Alias { get; set; }
        public string Password { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int ESTADOId { get; set; }
        public int PERSONAId { get; set; }
        public int ROLId { get; set; }
    
        public virtual ESTADO ESTADO { get; set; }
        public virtual PERSONA PERSONA { get; set; }
        public virtual ROL ROL { get; set; }
    }
}
